server:
  port: 9802
spring:
  application:
    name: order-service
  zipkin:
    base-url: http://127.0.0.1:9411/
    sender:
      type: web
  sleuth:
    http:
      enabled: true
  cloud:
    stream:
      bindings:
        orderSubmit:
          destination: orderSubmit
hystrix:
  threadpool:
    hiErrorPool:
      coreSize: 10
      maximumSize: 20
      maxQueueSize: 10

eureka:
  client:
    service-url:
      defaultZone: http://localhost:9800/eureka/