server:
  port: 9801
spring:
  application:
    name: oms-service
  zipkin:
    base-url: http://127.0.0.1:9411/
    sender:
      type: web
  sleuth:
    http:
      enabled: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:9800/eureka/